INSERT INTO `departamentos`(`ID_DEPARTAMENTO`, `NOMBRE_DEPARTAMENTO`, `ESTADO_DEPARTAMENTO`) VALUES (DEFAULT, "Recursos Humanos", DEFAULT);
INSERT INTO `departamentos`(`ID_DEPARTAMENTO`, `NOMBRE_DEPARTAMENTO`, `ESTADO_DEPARTAMENTO`) VALUES (DEFAULT, "Tecnologías de la Información", DEFAULT);
INSERT INTO `departamentos`(`ID_DEPARTAMENTO`, `NOMBRE_DEPARTAMENTO`, `ESTADO_DEPARTAMENTO`) VALUES (DEFAULT, "Ventas", DEFAULT);
INSERT INTO `departamentos`(`ID_DEPARTAMENTO`, `NOMBRE_DEPARTAMENTO`, `ESTADO_DEPARTAMENTO`) VALUES (DEFAULT, "Marketing", DEFAULT);