INSERT INTO `generos`(`ID_GENERO`, `NOMBRE_GENERO`, `ESTADO_GENERO`) VALUES (DEFAULT, "Masculino", 1);
INSERT INTO `generos`(`ID_GENERO`, `NOMBRE_GENERO`, `ESTADO_GENERO`) VALUES (DEFAULT, "Femenino", 1);
INSERT INTO `generos`(`ID_GENERO`, `NOMBRE_GENERO`, `ESTADO_GENERO`) VALUES (DEFAULT, "Otro", 1);