INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, PASSWORD_ROL) 
VALUES (1, 'Administrador', 'Administrador');

INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, PASSWORD_ROL) 
VALUES (2, 'Operador', '123');








--ADMINSTRADOR--
INSERT INTO EMPLEADOS 
(NOMBRE_EMPLEADO, APELLIDO_PATERNO, ID_GENERO, CURP_EMPLEADO, RFC_EMPLEADO, TELEFONO_EMPLEADO, CONTRATANTE, ID_DEPARTAMENTO, ID_ROL)
VALUES
('Administrador', 'Admin', 1, 'AAAA000101HDFXXX09', 'AAA010101AAA', '5512345678', NULL, 1, 1);
