CREATE TABLE PAISES (
    ID_PAIS INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_PAIS VARCHAR(255) NOT NULL,
    ESTADO_PAIS BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT UQ_NOMBRE_PAIS UNIQUE (NOMBRE_PAIS),
    CONSTRAINT CHK_ESTADO_PAIS CHECK (ESTADO_PAIS IN (0, 1))
);

CREATE TABLE ESTADOS (
    ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_ESTADO VARCHAR(255) NOT NULL,
    ID_PAIS INT NOT NULL,
    ESTADO_ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS),
    CONSTRAINT CHK_ESTADO_ESTADO CHECK (ESTADO_ESTADO IN (0, 1))
);

CREATE TABLE MUNICIPIOS (
    ID_MUNICIPIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_MUNICIPIO VARCHAR(255) NOT NULL,
    ID_ESTADO INT NOT NULL,
    ESTADO_MUNICIPIO BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO),
    CONSTRAINT CHK_ESTADO_MUNICIPIO CHECK (ESTADO_MUNICIPIO IN (0, 1))
);

CREATE TABLE DOMICILIOS (
    ID_DOMICILIO INT PRIMARY KEY AUTO_INCREMENT,
    CALLE VARCHAR(255) NOT NULL,
    NUMERO_EXTERIOR VARCHAR(255) NOT NULL,
    NUMERO_INTERIOR VARCHAR(255),
    COLONIA VARCHAR(255) NOT NULL,
    ID_MUNICIPIO INT NOT NULL,
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIOS(ID_MUNICIPIO)
);

CREATE TABLE GENEROS (
    ID_GENERO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_GENERO VARCHAR(255) NOT NULL,
    ESTADO_GENERO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT CHK_ESTADO_GENERO CHECK (ESTADO_GENERO IN (0, 1)),
    CONSTRAINT UQ_NOMBRE_GENERO UNIQUE (NOMBRE_GENERO)
);

CREATE TABLE DEPARTAMENTOS (
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(255) NOT NULL,
    ESTADO_DEPARTAMENTO BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT CHK_ESTADO_DEPARTAMENTO CHECK (ESTADO_DEPARTAMENTO IN (0, 1)),
    CONSTRAINT UQ_NOMBRE_DEPARTAMENTO UNIQUE (NOMBRE_DEPARTAMENTO)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_EMPLEADO VARCHAR(255) NOT NULL,
    APELLIDO_PATERNO VARCHAR(255),
    APELLIDO_MATERNO VARCHAR(255),
    ID_GENERO INT NOT NULL,
    CURP_EMPLEADO VARCHAR(18) NOT NULL,
    RFC_EMPLEADO VARCHAR(13) NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(10) NOT NULL,
    CONTRATANTE INT NOT NULL,
    FECHA_CONTRATACION DATE NOT NULL DEFAULT CURRENT_DATE,
    ID_DEPARTAMENTO INT NOT NULL,
    ID_DOMICILIO INT NOT NULL,
    FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID_GENERO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
    FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIOS(ID_DOMICILIO),
    FOREIGN KEY (CONTRATANTE) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT UQ_CURP_EMPLEADO UNIQUE (CURP_EMPLEADO),
    CONSTRAINT UQ_RFC_EMPLEADO UNIQUE (RFC_EMPLEADO),
    CONSTRAINT CHK_CURP_EMPLEADO CHECK (CURP_EMPLEADO REGEXP '^([A-Z][AEIOUX][A-Z]{2}[0-9]{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12][0-9]|3[01])[HM](?:AS|B[CS]|C[CLMSH]|D[FG]|G[TR]|HG|JC|M[CNS]|N[ETL]|OC|PL|Q[TR]|S[PLR]|T[CSL]|VZ|YN|ZS)[B-DF-HJ-NP-TV-Z]{3}[A-Z0-9])([0-9])$'),
    CONSTRAINT CHK_RFC_EMPLEADO CHECK (RFC_EMPLEADO REGEXP '^[A-ZÑ&]{3,4}[0-9]{6}(?:[A-Z0-9]{3})?$'),
    CONSTRAINT CHK_TELEFONO_EMPLEADO CHECK (TELEFONO_EMPLEADO REGEXP '^[0-9]{10}$'),
    CONSTRAINT UQ_TELEFONO_EMPLEADO UNIQUE (TELEFONO_EMPLEADO),
    CONSTRAINT CHK_APELLIDOS CHECK (APELLIDO_PATERNO IS NOT NULL OR APELLIDO_MATERNO IS NOT NULL)
);

CREATE TABLE CORREOS (
    ID_EMPLEADO INT NOT NULL,
    CORREO_EMPLEADO VARCHAR(255) NOT NULL,
    TIPO_CORREO VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT UQ_CORREO_EMPLEADO UNIQUE (CORREO_EMPLEADO),
    CONSTRAINT CHK_CORREO_EMPLEADO CHECK (CORREO_EMPLEADO REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'),
    CONSTRAINT CHK_TIPO_CORREO CHECK (TIPO_CORREO IN ('principal', 'secundario')),
    CONSTRAINT UQ_TIPO_CORREO UNIQUE (ID_EMPLEADO, TIPO_CORREO)
);